CREATE TABLE `booksV2` (
  `id` int(11) NOT NULL,
  `title` text NOT NULL,
  `description` text NOT NULL,
  `year` int(11) NOT NULL,
  `pages` int(11) NOT NULL,
  `clicks` int(11) NOT NULL,
  `views` int(11) NOT NULL,
  `date` date NOT NULL,
  `deleted` tinyint(1) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;